# Generated by Django 4.2.5 on 2023-09-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='tiyulo',
            new_name='titulo',
        ),
    ]
