# Generated by Django 4.2.5 on 2023-09-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_tiyulo_evento_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data_criaco',
            new_name='data_criacao',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(verbose_name='Data do Evento'),
        ),
    ]
